---
- name: Get Arch variables
  ansible.builtin.command: dpkg --print-architecture
  register: arch_results
  changed_when: arch_results.rc != 0

- name: Get Ubuntu release variables
  ansible.builtin.command: lsb_release -cs
  register: release_results
  changed_when: release_results.rc != 0

- name: Create keyrings directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.gpg
    mode: "0644"

- name: Add Docker apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch_results }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ release_results }} stable"
    state: present

- name: Install containerd
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: "yes"
    name: "containerd.io"

- name: Create containerd config directory
  become: true
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Configure containerd
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      containerd config default | sudo tee /etc/containerd/config.toml
  changed_when: false

- name: Restart containerd systemd
  become: true
  ansible.builtin.systemd:
    name: containerd.service
    state: restarted
