---
all:
  vars:
    ansible_user: k8s-user
    ansible_password: zaq12wsx
  children:
    k8s-nodes:
      hosts:
        master-0:
          ansible_host: 192.168.0.80
        worker-0:
          ansible_host: 192.168.0.81
        worker-1:
          ansible_host: 192.168.0.82
      vars:
        ansible_ssh_private_key_file: /home/k8s-user/.ssh/id_ed25519