- name: Create Directory ~/.ssh
  become: yes
  file: dest=/home/k8s-user/.ssh state=directory state=directory owner=k8s-user group=k8s-user

- name: Generate SSH Key
  become: yes
  openssh_keypair: 
    path: /home/k8s-user/.ssh/id_ed25519
    type: ed25519


