- name: Create Directory ~/.ssh
  become: true
  ansible.builtin.file:
    dest: /home/k8s-user/.ssh
    state: directory
    mode: "0700"
    owner: k8s-user
    group: k8s-user

- name: Generate SSH Key
  become: true
  community.crypto.openssh_keypair:
    path: /home/k8s-user/.ssh/id_ed25519
    type: ed25519
