---
all:
  hosts:
    master-0:
      ansible_host: 192.168.0.80
    worker-0:
      ansible_host: 192.168.0.81
    worker-1:
      ansible_host: 192.168.0.82
  children:
    k8s_ansible_leader_host:
      hosts:
        master-0:
          ansible_host: 192.168.0.80
    k8s_ansible_worker_hosts:
      hosts:
        worker-0:
          ansible_host: 192.168.0.81
        worker-1:
          ansible_host: 192.168.0.82
