- name: Copy Public SSH Key
  ansible.builtin.copy:
    src: /home/k8s-user/.ssh/id_ed25519.pub
    dest: /home/k8s-user/.ssh/id_ed25519.pub

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: k8s-user
    state: present
    key: "{{ lookup('file', '/home/k8s-user/.ssh/id_ed25519.pub') }}"

- name: Configure sshd_config
  become: yes
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" } 

- name: restart sshd
  become: yes
  service: name=sshd state=restarted