- name: Copy Public SSH Key
  ansible.builtin.copy:
    src: "/home/{{ ansible_user }}/.ssh/id_ed25519.pub"
    dest: "/home/{{ ansible_user }}/.ssh/id_ed25519.pub"
    mode: "0644"

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/id_ed25519.pub') }}"

- name: Configure sshd_config
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }

- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
