---
- name: Disable swap
  become: true
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Configure CRI endpoints
  become: true
  ansible.builtin.blockinfile:
    path: /etc/crictl.yaml
    block: |
      'runtime-endpoint: unix:///var/run/containerd/containerd.sock'
      'image-endpoint: unix:///var/run/containerd/containerd.sock'
      'timeout: 10'
    marker: ""
    create: "yes"
    state: present
    mode: "0644"
