---
- name: Configure Kernel
  become: true
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: false
  loop: 
    - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { key: "vm.overcommit_memory", value: "1" }
    - { key: "vm.panic_on_oom", value: "0" }
    - { key: "kernel.panic", value: "10" }
    - { key: "kernel.panic_on_oops", value: "1" }
    - { key: "kernel.keys.root_maxkeys", value: "1000000" }
    - { key: "kernel.keys.root_maxbytes", value: "25000000" }
    - { key: "net.ipv4.conf.*.rp_filter", value: "0" }

- name: Add Kubernetes GPG key
  become: true
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes apt repository
  become: true
  apt_repository:
    repo:  deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install containerd
  become: true
  apt:
    state: present
    update_cache: yes
    name: "{{ item.key }}={{ item.value }}"
  loop: 
    - { key: "kubelet", value: "1.27.1-00" }
    - { key: "kubeadm", value: "1.27.1-00" }
    - { key: "kubectl", value: "1.27.1-00" }