name: Ansible Lint
run-name: ${{ github.workflow }} ( ${{ github.ref_name }} )

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@main
        with:
          working_directory: ./ansible
